export * from './about/about.component'
export * from './skills/skills.component'
export * from './contact/contact.component'
export * from './home/home.component'
export * from './proyects/proyects.component'